# Generated by Django 2.2.4 on 2019-08-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('processed', 'Processed')], max_length=256)),
                ('warehouse_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.WarehouseAccount')),
            ],
        ),
    ]
