# Generated by Django 2.2.4 on 2019-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseaccount',
            name='account_name',
            field=models.CharField(default='Account 1', max_length=256),
            preserve_default=False,
        ),
    ]
