# Generated by Django 2.2.4 on 2019-08-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_warehouseaccount_account_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='warehouseaccount',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
    ]
