# Generated by Django 2.2.4 on 2019-08-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=256)),
                ('order_status', models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('processed', 'Processed')], max_length=256)),
            ],
        ),
    ]
