# Generated by Django 2.2.4 on 2019-08-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_order_store_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='store_order_pk',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
